"""
Django settings for agdevops project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import json
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


DEFAULT_GRAFANA_DASHBOARDS = [
    {
        'key': 'apm-overview',
        'title': 'APM 全链路总览',
        'slug': 'apm-overview',
        'path': '/d/apm-overview',
        'panel_count': 18,
        'tags': ['SkyWalking', '应用', 'SLA'],
        'description': '面向应用负责人查看服务吞吐、慢调用与错误率。',
    },
    {
        'key': 'infra-overview',
        'title': '基础设施总览',
        'slug': 'infra-overview',
        'path': '/d/infra-overview',
        'panel_count': 14,
        'tags': ['Node', 'CPU', 'Memory'],
        'description': '聚合节点 CPU、内存、磁盘与 Pod 负载走势。',
    },
    {
        'key': 'log-drilldown',
        'title': '日志钻取看板',
        'slug': 'log-drilldown',
        'path': '/d/log-drilldown',
        'panel_count': 12,
        'tags': ['Loki', 'Error', 'Audit'],
        'description': '配合日志中心快速回放错误时段与关键日志。',
    },
    {
        'key': 'ingress-slo',
        'title': '入口流量与 SLO',
        'slug': 'ingress-slo',
        'path': '/d/ingress-slo',
        'panel_count': 10,
        'tags': ['Nginx', 'Latency', 'Availability'],
        'description': '聚焦入口 QPS、响应时间分位和可用性目标。',
    },
    {
        'key': 'kubernetes-compute-resources-workload',
        'title': 'Kubernetes / Compute Resources / Workload',
        'slug': 'kubernetes-compute-resources-workload',
        'path': '/d/k8s-resources-workload',
        'panel_count': 16,
        'tags': ['Kubernetes', 'Workload', 'Compute'],
        'description': '按 namespace 和 workload 查看 Kubernetes 工作负载资源。',
    },
]


def _json_env(name, default):
    raw = os.getenv(name, '').strip()
    if not raw:
        return default
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        return default


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ag#xxnjm^46$=ye()w$yma8r8oy3&wfq!8_=bm!kwe0e((&y3-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'rest_framework',
    'rest_framework.authtoken',
    'django_filters',
    'corsheaders',
    'channels',
    # Local
    'ops.apps.OpsConfig',
    'sqlaudit',
    'marketplace',
    'cmdb',
    'iac',
    'multicloud',
    'aiops.apps.AiopsConfig',
    'rbac',
    'eventwall',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'agdevops.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'agdevops.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS
CORS_ALLOW_ALL_ORIGINS = True

# DRF
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
    ],
}

# Loki
LOKI_URL = 'http://47.95.15.209:33100'

LOG_PROVIDER_CONFIGS = {
    'loki': {
        'endpoint': os.getenv('LOKI_URL', LOKI_URL),
    },
    'elk': {
        'endpoint': os.getenv('ELK_URL', ''),
        'auth_type': os.getenv('ELK_AUTH_TYPE', 'none'),
        'username': os.getenv('ELK_USERNAME', ''),
        'password': os.getenv('ELK_PASSWORD', ''),
        'api_key': os.getenv('ELK_API_KEY', ''),
        'bearer_token': os.getenv('ELK_BEARER_TOKEN', ''),
        'index_pattern': os.getenv('ELK_INDEX_PATTERN', 'logs-*'),
        'time_field': os.getenv('ELK_TIME_FIELD', '@timestamp'),
        'message_fields': os.getenv('ELK_MESSAGE_FIELDS', 'message,log,msg'),
    },
    'sls': {
        'endpoint': os.getenv('ALIYUN_SLS_ENDPOINT', ''),
        'project': os.getenv('ALIYUN_SLS_PROJECT', ''),
        'logstore': os.getenv('ALIYUN_SLS_LOGSTORE', ''),
        'topic': os.getenv('ALIYUN_SLS_TOPIC', ''),
        'access_key_id': os.getenv('ALIYUN_SLS_ACCESS_KEY_ID', ''),
        'access_key_secret': os.getenv('ALIYUN_SLS_ACCESS_KEY_SECRET', ''),
    },
}

OBSERVABILITY_CONFIG = {
    'tracing': {
        'default_provider': os.getenv('TRACING_DEFAULT_PROVIDER', 'skywalking'),
    },
    'skywalking': {
        'provider': 'skywalking',
        'enabled': os.getenv('SKYWALKING_ENABLED', '1') != '0',
        'ui_url': os.getenv('SKYWALKING_UI_URL', ''),
        'oap_url': os.getenv('SKYWALKING_OAP_URL', ''),
        'graphql_path': os.getenv('SKYWALKING_GRAPHQL_PATH', '/graphql'),
        'default_layer': os.getenv('SKYWALKING_DEFAULT_LAYER', ''),
        'demo_mode': os.getenv('SKYWALKING_DEMO_MODE', '1') == '1',
    },
    'tempo': {
        'provider': 'tempo',
        'enabled': os.getenv('TEMPO_ENABLED', '0') == '1',
        'ui_url': os.getenv('TEMPO_UI_URL', ''),
        'query_url': os.getenv('TEMPO_QUERY_URL', ''),
        'demo_mode': os.getenv('TEMPO_DEMO_MODE', '1') == '1',
    },
    'jaeger': {
        'provider': 'jaeger',
        'enabled': os.getenv('JAEGER_ENABLED', '0') == '1',
        'ui_url': os.getenv('JAEGER_UI_URL', ''),
        'query_url': os.getenv('JAEGER_QUERY_URL', ''),
        'demo_mode': os.getenv('JAEGER_DEMO_MODE', '1') == '1',
    },
    'zipkin': {
        'provider': 'zipkin',
        'enabled': os.getenv('ZIPKIN_ENABLED', '0') == '1',
        'ui_url': os.getenv('ZIPKIN_UI_URL', ''),
        'query_url': os.getenv('ZIPKIN_QUERY_URL', ''),
        'demo_mode': os.getenv('ZIPKIN_DEMO_MODE', '1') == '1',
    },
    'grafana': {
        'enabled': os.getenv('GRAFANA_ENABLED', '1') != '0',
        'url': os.getenv('GRAFANA_URL', ''),
        'default_path': os.getenv('GRAFANA_DEFAULT_PATH', ''),
        'demo_mode': os.getenv('GRAFANA_DEMO_MODE', '1') == '1',
        'dashboards': _json_env('GRAFANA_DASHBOARDS_JSON', DEFAULT_GRAFANA_DASHBOARDS),
    },
}

# ASGI / Channels
ASGI_APPLICATION = 'agdevops.asgi.application'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}
