import request from '../request'

export const getDashboardStats = () => request.get('/dashboard/stats/')

export const getHosts = (params) => request.get('/hosts/', { params })
export const getHost = (id) => request.get(`/hosts/${id}/`)
export const createHost = (data) => request.post('/hosts/', data)
export const updateHost = (id, data) => request.put(`/hosts/${id}/`, data)
export const deleteHost = (id) => request.delete(`/hosts/${id}/`)
export const testHostConnection = (id) => request.post(`/hosts/${id}/test_connection/`)
export const refreshHostInfo = (id) => request.post(`/hosts/${id}/refresh_info/`)
export const getHostTasks = (params) => request.get('/host-tasks/', { params })
export const getHostTask = (id) => request.get(`/host-tasks/${id}/`)
export const createHostTask = (data) => request.post('/host-tasks/', data)
export const rerunHostTask = (id) => request.post(`/host-tasks/${id}/rerun/`)
export const cancelHostTask = (id) => request.post(`/host-tasks/${id}/cancel/`)
export const batchCancelHostTasks = (data) => request.post('/host-tasks/batch_cancel/', data)
export const getHostTaskStats = () => request.get('/host-tasks/stats/')
export const getHostTaskTargets = (params) => request.get('/host-tasks/host_options/', { params })
export const getHostTaskTemplates = (params) => request.get('/host-task-templates/', { params })
export const createHostTaskTemplate = (data) => request.post('/host-task-templates/', data)
export const updateHostTaskTemplate = (id, data) => request.put(`/host-task-templates/${id}/`, data)
export const deleteHostTaskTemplate = (id) => request.delete(`/host-task-templates/${id}/`)
export const getHostTaskSchedules = (params) => request.get('/host-task-schedules/', { params })
export const getHostTaskSchedule = (id) => request.get(`/host-task-schedules/${id}/`)
export const createHostTaskSchedule = (data) => request.post('/host-task-schedules/', data)
export const updateHostTaskSchedule = (id, data) => request.put(`/host-task-schedules/${id}/`, data)
export const deleteHostTaskSchedule = (id) => request.delete(`/host-task-schedules/${id}/`)
export const getHostTaskScheduleStats = () => request.get('/host-task-schedules/stats/')
export const previewHostTaskSchedule = (data) => request.get('/host-task-schedules/preview_next_runs/', {
  params: {
    ...data,
    payload: JSON.stringify(data?.payload || {}),
    selection_filters: JSON.stringify(data?.selection_filters || {}),
    target_host_ids: JSON.stringify(data?.target_host_ids || []),
  },
})
export const toggleHostTaskSchedule = (id) => request.post(`/host-task-schedules/${id}/toggle_enabled/`)
export const runHostTaskScheduleNow = (id) => request.post(`/host-task-schedules/${id}/run_now/`)
export const getHostTaskScheduleExecutions = (params) => request.get('/host-task-schedule-executions/', { params })
export const getHostTaskScheduleExecution = (id) => request.get(`/host-task-schedule-executions/${id}/`)

export const getDeployments = (params) => request.get('/deployments/', { params })
export const createDeployment = (data) => request.post('/deployments/', data)
export const updateDeployment = (id, data) => request.put(`/deployments/${id}/`, data)
export const deleteDeployment = (id) => request.delete(`/deployments/${id}/`)
export const approveDeployment = (id, data = {}) => request.post(`/deployments/${id}/approve/`, data)
export const rejectDeployment = (id, data = {}) => request.post(`/deployments/${id}/reject/`, data)
export const rerunDeployment = (id, data = {}) => request.post(`/deployments/${id}/rerun/`, data)
export const rollbackDeployment = (id, data = {}) => request.post(`/deployments/${id}/rollback/`, data)
export const advanceDeploymentBatch = (id, data = {}) => request.post(`/deployments/${id}/advance_batch/`, data)
export const stopDeployment = (id) => request.post(`/deployments/${id}/stop/`)
export const startDeployment = (id) => request.post(`/deployments/${id}/start/`)
export const removeDeployment = (id) => request.post(`/deployments/${id}/remove/`)
export const getDeploymentLogs = (id, tail = 100) => request.get(`/deployments/${id}/logs/`, { params: { tail } })
export const getDeploymentStatus = (id) => request.get(`/deployments/${id}/status_detail/`)
export const getDeploymentApprovalFlows = (params) => request.get('/deployment-approval-flows/', { params })
export const createDeploymentApprovalFlow = (data) => request.post('/deployment-approval-flows/', data)
export const updateDeploymentApprovalFlow = (id, data) => request.put(`/deployment-approval-flows/${id}/`, data)
export const deleteDeploymentApprovalFlow = (id) => request.delete(`/deployment-approval-flows/${id}/`)
export const getTransactionTickets = (params) => request.get('/transaction-tickets/', { params })
export const createTransactionTicket = (data) => request.post('/transaction-tickets/', data)
export const updateTransactionTicket = (id, data) => request.patch(`/transaction-tickets/${id}/`, data)
export const deleteTransactionTicket = (id) => request.delete(`/transaction-tickets/${id}/`)
export const approveTransactionTicket = (id) => request.post(`/transaction-tickets/${id}/approve/`)
export const rejectTransactionTicket = (id) => request.post(`/transaction-tickets/${id}/reject/`)
export const startProcessTransactionTicket = (id) => request.post(`/transaction-tickets/${id}/start_process/`)
export const completeTransactionTicket = (id) => request.post(`/transaction-tickets/${id}/complete/`)

export const getAlerts = (params) => request.get('/alerts/', { params })
export const updateAlert = (id, data) => request.patch(`/alerts/${id}/`, data)
export const deleteAlert = (id) => request.delete(`/alerts/${id}/`)

export const getLogs = (params) => request.get('/logs/', { params })

export const getUsers = (params) => request.get('/users/', { params })

export const getLokiLabels = (params) => request.get('/loki/labels/', { params })
export const getLokiLabelValues = (name, params) => request.get(`/loki/label/${name}/values/`, { params })
export const queryLokiLogs = (params) => request.get('/loki/query_range/', { params })
export const getLokiSeries = (params) => request.get('/loki/series/', { params })

export const getLogProviders = () => request.get('/log/providers/')
export const getLogProviderCatalog = (provider, data) => request.post(`/log/providers/${provider}/catalog/`, data)
export const queryLogs = (data) => request.post('/log/query/', data)

export const getLogDataSources = (params) => request.get('/log/datasources/', { params })
export const createLogDataSource = (data) => request.post('/log/datasources/', data)
export const updateLogDataSource = (id, data) => request.put(`/log/datasources/${id}/`, data)
export const deleteLogDataSource = (id) => request.delete(`/log/datasources/${id}/`)
export const testLogDataSource = (id) => request.post(`/log/datasources/${id}/test_connection/`)

export const getObservabilityOverview = (params) => request.get('/observability/overview/', { params })
export const getObservabilityDataSourceLinks = (params) => request.get('/observability/datasource-links/', { params })
export const createObservabilityDataSourceLink = (data) => request.post('/observability/datasource-links/', data)
export const updateObservabilityDataSourceLink = (id, data) => request.put(`/observability/datasource-links/${id}/`, data)
export const deleteObservabilityDataSourceLink = (id) => request.delete(`/observability/datasource-links/${id}/`)
export const resolveTraceToLogs = (data) => request.post('/observability/datasource-links/resolve_trace_to_logs/', data)
export const resolveLogToTrace = (data) => request.post('/observability/datasource-links/resolve_log_to_trace/', data)
export const resolveTraceToGrafana = (data) => request.post('/observability/datasource-links/resolve_trace_to_grafana/', data)
export const resolveLogToGrafana = (data) => request.post('/observability/datasource-links/resolve_log_to_grafana/', data)
export const resolveGrafanaToLogs = (data) => request.post('/observability/datasource-links/resolve_grafana_to_logs/', data)
export const resolveGrafanaToTrace = (data) => request.post('/observability/datasource-links/resolve_grafana_to_trace/', data)
export const getGrafanaConfig = () => request.get('/observability/grafana/config/')
export const updateGrafanaConfig = (data) => request.put('/observability/grafana/config/', data)
export const getTracingProviders = () => request.get('/observability/tracing/providers/')
export const getTracingDataSources = (params) => request.get('/observability/tracing/datasources/', { params })
export const createTracingDataSource = (data) => request.post('/observability/tracing/datasources/', data)
export const updateTracingDataSource = (id, data) => request.put(`/observability/tracing/datasources/${id}/`, data)
export const deleteTracingDataSource = (id) => request.delete(`/observability/tracing/datasources/${id}/`)
export const testTracingDataSource = (id) => request.post(`/observability/tracing/datasources/${id}/test_connection/`)
export const getTracingCatalog = (params) => request.get('/observability/tracing/catalog/', { params })
export const searchTracing = (data) => request.post('/observability/tracing/search/', data)
export const getTraceDetail = (traceId, params) => request.get(`/observability/tracing/traces/${traceId}/`, { params })
