PERMISSION_DEFINITIONS = [
    ('ops.dashboard.view', '查看运维仪表盘', 'ops', '访问首页运维统计与最近动态'),
    ('ops.host.view', '查看主机', 'ops', '查看主机列表与详情'),
    ('ops.host.manage', '管理主机', 'ops', '新增、编辑、删除、测试、刷新主机'),
    ('ops.host.terminal', '使用 WebShell', 'ops', '通过浏览器进入主机终端'),
    ('ops.host.execute', '执行主机任务', 'ops', '通过任务中心批量执行主机巡检与运维命令'),
    ('ops.host.schedule.view', '查看定时任务', 'ops', '查看主机定时编排、执行记录与下次执行时间'),
    ('ops.host.schedule.manage', '管理定时任务', 'ops', '创建、编辑、启停和删除主机定时编排'),
    ('ops.host.schedule.execute', '执行定时任务', 'ops', '手动触发主机定时编排并复用 SSH/Ansible 执行链路'),
    ('ops.deployment.view', '查看应用发布', 'ops', '查看公司应用发布记录、状态与日志'),
    ('ops.deployment.manage', '管理应用发布', 'ops', '创建发布申请、重试、回滚、启停和下线应用'),
    ('ops.deployment.approve', '审批应用发布', 'ops', '审批通过或驳回应用发布申请'),
    ('ops.ticket.view', '查看事务工单', 'ops', '查看事务工单列表、详情与处理状态'),
    ('ops.ticket.manage', '管理事务工单', 'ops', '创建、编辑、删除并推进事务工单执行'),
    ('ops.ticket.approve', '审批事务工单', 'ops', '审批通过或驳回事务工单'),
    ('ops.alert.view', '查看告警', 'ops', '查看告警列表'),
    ('ops.alert.manage', '管理告警', 'ops', '确认、编辑、删除告警'),
    ('ops.log.entry.view', '查看内置日志', 'ops', '查看平台内置日志表'),
    ('ops.log.entry.manage', '管理内置日志', 'ops', '新增、编辑、删除平台内置日志表数据'),
    ('ops.log.datasource.view', '查看日志数据源', 'ops', '查看日志数据源与供应商能力'),
    ('ops.log.datasource.manage', '管理日志数据源', 'ops', '新增、编辑、删除、测试日志数据源'),
    ('ops.log.query', '查询日志', 'ops', '执行 Loki、ELK、SLS 日志检索'),
    ('ops.trace.view', '查看链路追踪', 'ops', '查看 SkyWalking 链路、调用拓扑与 Span 详情'),
    ('ops.grafana.view', '查看 Grafana 大屏', 'ops', '查看 Grafana 观测大屏与推荐仪表板'),
    ('ops.k8s.view', '查看 K8s 集群', 'ops', '查看集群、命名空间与资源列表'),
    ('ops.k8s.manage', '管理 K8s 集群', 'ops', '维护集群连接并执行集群管理动作'),
    ('ops.k8s.exec', '执行 K8s Pod 命令', 'ops', '通过浏览器对 Pod 执行命令并进入轻量控制台'),
    ('ops.docker.view', '查看 Docker 环境', 'ops', '查看 Docker 主机、容器、镜像与日志'),
    ('ops.docker.manage', '管理 Docker 环境', 'ops', '维护 Docker 主机并执行容器操作'),
    ('ops.middleware.view', '查看常用中间件', 'ops', '查看 Redis、RocketMQ、Elasticsearch 的运行态势与演示数据'),
    ('ops.middleware.manage', '管理常用中间件', 'ops', '执行 Redis、RocketMQ、Elasticsearch 的演示管理动作'),
    ('ops.nginx.view', '查看 Nginx 配置', 'ops', '查看 Nginx 环境、证书、域名与路由'),
    ('ops.nginx.manage', '管理 Nginx 配置', 'ops', '维护 Nginx 环境并推送证书和配置'),
    ('ops.iac.view', '查看 Terraform IaC', 'ops', '查看 Terraform 基础设施即代码方案与生成结果'),
    ('ops.iac.manage', '管理 Terraform IaC', 'ops', '创建、编辑、删除并导出 Terraform 基础设施方案'),
    ('ops.iac.execute', '执行 Terraform IaC', 'ops', '执行 Terraform init/plan/apply/destroy 并同步 CMDB'),
    ('ops.multicloud.view', '查看多云环境', 'ops', '查看云账号、云环境、云资源、成本与同步记录'),
    ('ops.multicloud.manage', '管理多云环境', 'ops', '维护多云账号与环境配置，并执行连通性检测'),
    ('ops.multicloud.sync', '同步多云环境', 'ops', '执行多云资源同步、巡检和 CMDB 对齐'),
    ('cmdb.dashboard.view', '查看 CMDB 总览', 'cmdb', '查看 CMDB 仪表盘指标'),
    ('cmdb.ci.view', '查看 CMDB 资源', 'cmdb', '查看 CI 类型、配置项、关系、资源树与申请单'),
    ('cmdb.ci.manage', '管理 CMDB 资源', 'cmdb', '维护 CI 类型、配置项、关系、资源树与成本记录'),
    ('cmdb.topology.view', '查看 CMDB 拓扑', 'cmdb', '查看资源拓扑与资源地图'),
    ('cmdb.cost.view', '查看 CMDB 成本', 'cmdb', '查看成本报表与优化建议'),
    ('cmdb.request.submit', '提交资源申请', 'cmdb', '提交新的资源申请'),
    ('cmdb.request.approve', '审批资源申请', 'cmdb', '审批或交付资源申请'),
    ('marketplace.template.view', '查看服务模板', 'marketplace', '查看工具市场模板与部署信息'),
    ('marketplace.deployment.view', '查看服务部署', 'marketplace', '查看工具市场部署记录与日志'),
    ('marketplace.deployment.manage', '管理服务部署', 'marketplace', '发起部署、启停、卸载服务'),
    ('sqlaudit.datasource.view', '查看 SQL 数据源', 'sqlaudit', '查看数据库数据源与库列表'),
    ('sqlaudit.datasource.manage', '管理 SQL 数据源', 'sqlaudit', '维护数据库数据源与测试连通性'),
    ('sqlaudit.order.view', '查看 SQL 工单', 'sqlaudit', '查看 SQL 工单与检查结果'),
    ('sqlaudit.order.submit', '提交 SQL 工单', 'sqlaudit', '创建 SQL 变更工单并执行检查'),
    ('sqlaudit.order.review', '审核 SQL 工单', 'sqlaudit', '审核通过或驳回 SQL 工单'),
    ('sqlaudit.order.execute', '执行 SQL 工单', 'sqlaudit', '执行已审核通过的 SQL 工单'),
    ('sqlaudit.query.view', '查看 SQL 查询记录', 'sqlaudit', '查看 SQL 查询历史'),
    ('sqlaudit.query.execute', '执行 SQL 查询', 'sqlaudit', '提交只读 SQL 查询'),
    ('eventwall.view', '查看事件墙', 'eventwall', '查看平台事件流、关联链路与审计概览'),
    ('aiops.chat.view', '查看 AIOps 机器人', 'aiops', '在页面右下角打开 AIOps 智能助手并发起对话'),
    ('aiops.chat.analyze', '使用 AIOps 关联分析', 'aiops', '基于资源、告警、日志、事件和变更做关联分析'),
    ('aiops.task.generate', '生成 AIOps 任务草稿', 'aiops', '通过机器人生成主机巡检、命令和执行草稿'),
    ('aiops.task.execute', '执行 AIOps 任务', 'aiops', '通过机器人确认并触发任务中心执行'),
    ('aiops.config.view', '查看 AIOps 配置', 'aiops', '查看模型、MCP、Skill 和机器人安全配置'),
    ('aiops.config.manage', '管理 AIOps 配置', 'aiops', '维护模型 API、MCP、Skill、Prompt 与执行策略'),
    ('aiops.audit.view', '查看 AIOps 审计', 'aiops', '查看机器人会话、工具调用和动作执行审计'),
    ('rbac.user.view', '查看用户', 'rbac', '查看用户、角色、用户组信息'),
    ('rbac.user.manage', '管理用户', 'rbac', '新增、编辑、禁用、重置用户密码'),
    ('rbac.role.view', '查看角色', 'rbac', '查看角色与权限绑定'),
    ('rbac.role.manage', '管理角色', 'rbac', '新增、编辑、删除角色'),
    ('rbac.group.view', '查看用户组', 'rbac', '查看用户组与成员关系'),
    ('rbac.group.manage', '管理用户组', 'rbac', '新增、编辑、删除用户组'),
    ('rbac.permission.view', '查看权限字典', 'rbac', '查看系统权限清单'),
]


BUILTIN_ROLES = [
    {
        'code': 'platform-admin',
        'name': '平台管理员',
        'description': '拥有平台全部权限。',
        'permissions': ['*'],
    },
    {
        'code': 'ops-admin',
        'name': '运维管理员',
        'description': '负责主机、部署、容器、Nginx、日志与 CMDB 维护。',
        'permissions': [
            'ops.dashboard.view', 'ops.host.view', 'ops.host.manage', 'ops.host.terminal', 'ops.host.execute',
            'ops.host.schedule.view', 'ops.host.schedule.manage', 'ops.host.schedule.execute',
            'ops.deployment.view', 'ops.deployment.manage', 'ops.deployment.approve',
            'ops.ticket.view', 'ops.ticket.manage', 'ops.ticket.approve',
            'ops.alert.view', 'ops.alert.manage',
            'ops.log.entry.view', 'ops.log.datasource.view', 'ops.log.datasource.manage', 'ops.log.query',
            'ops.trace.view', 'ops.grafana.view',
            'ops.k8s.view', 'ops.k8s.manage', 'ops.k8s.exec', 'ops.docker.view', 'ops.docker.manage',
            'ops.middleware.view', 'ops.middleware.manage',
            'ops.nginx.view', 'ops.nginx.manage', 'ops.iac.view', 'ops.iac.manage', 'ops.iac.execute',
            'ops.multicloud.view', 'ops.multicloud.manage', 'ops.multicloud.sync',
            'eventwall.view',
            'aiops.chat.view', 'aiops.chat.analyze', 'aiops.task.generate', 'aiops.task.execute', 'aiops.config.view', 'aiops.audit.view',
            'cmdb.dashboard.view', 'cmdb.ci.view',
            'cmdb.ci.manage', 'cmdb.topology.view', 'cmdb.cost.view', 'cmdb.request.submit',
            'cmdb.request.approve', 'marketplace.template.view', 'marketplace.deployment.view',
            'marketplace.deployment.manage',
        ],
    },
    {
        'code': 'developer',
        'name': '研发工程师',
        'description': '可查看环境信息、日志并提交 SQL 与资源申请。',
        'permissions': [
            'ops.dashboard.view', 'ops.host.view', 'ops.host.schedule.view', 'ops.deployment.view', 'ops.ticket.view', 'ops.alert.view',
            'ops.log.query', 'ops.log.datasource.view', 'ops.trace.view', 'ops.grafana.view', 'ops.middleware.view',
            'ops.iac.view', 'ops.iac.manage', 'ops.iac.execute', 'ops.multicloud.view', 'eventwall.view',
            'aiops.chat.view', 'aiops.chat.analyze', 'aiops.task.generate',
            'cmdb.dashboard.view', 'cmdb.ci.view',
            'cmdb.topology.view', 'cmdb.cost.view', 'cmdb.request.submit', 'marketplace.template.view',
            'marketplace.deployment.view', 'sqlaudit.datasource.view', 'sqlaudit.order.view',
            'sqlaudit.order.submit', 'sqlaudit.query.view', 'sqlaudit.query.execute',
        ],
    },
    {
        'code': 'security-auditor',
        'name': '审计员',
        'description': '查看日志、安全告警并审核 SQL 工单。',
        'permissions': [
            'ops.dashboard.view', 'ops.alert.view', 'ops.log.datasource.view', 'ops.log.query', 'ops.trace.view', 'ops.grafana.view',
            'ops.multicloud.view', 'eventwall.view', 'aiops.chat.view', 'aiops.chat.analyze',
            'cmdb.dashboard.view', 'cmdb.topology.view', 'cmdb.cost.view', 'sqlaudit.datasource.view',
            'sqlaudit.order.view', 'sqlaudit.order.review', 'sqlaudit.query.view',
        ],
    },
    {
        'code': 'read-only',
        'name': '只读访客',
        'description': '只能浏览各模块的只读信息。',
        'permissions': [
            'ops.dashboard.view', 'ops.host.view', 'ops.host.schedule.view', 'ops.deployment.view', 'ops.ticket.view', 'ops.alert.view',
            'ops.log.entry.view', 'ops.log.datasource.view', 'ops.trace.view', 'ops.grafana.view', 'ops.k8s.view', 'ops.docker.view',
            'ops.middleware.view', 'ops.nginx.view', 'ops.iac.view', 'ops.multicloud.view',
            'cmdb.dashboard.view', 'cmdb.ci.view', 'cmdb.topology.view',
            'cmdb.cost.view', 'marketplace.template.view', 'marketplace.deployment.view',
            'sqlaudit.datasource.view', 'sqlaudit.order.view', 'sqlaudit.query.view',
            'eventwall.view', 'aiops.chat.view',
            'rbac.user.view', 'rbac.role.view', 'rbac.group.view', 'rbac.permission.view',
        ],
    },
]
