from datetime import timedelta

from django.core.management.base import BaseCommand
from django.utils import timezone

from eventwall.models import EventRecord
from eventwall.services import build_resource, record_event


DEMO_WINDOW_MINUTES = 7 * 24 * 60 - 1
EXCLUDED_DEMO_ENVIRONMENTS = {'prod', 'staging'}
APPLICATION_RELEASE_ACTIONS = {
    'deploy_start',
    'deploy_finish',
    'approval_finish',
    'rollback',
    'service_deployment',
}
APPLICATION_RELEASE_RESOURCE_TYPES = {
    'deployment',
    'service_deployment',
    'deployment_approval_flow',
}


class Command(BaseCommand):
    help = '生成事件墙最近 7 天演示数据'

    def handle(self, *args, **options):
        EventRecord.objects.filter(is_demo=True).delete()
        self.now = timezone.localtime().replace(second=0, microsecond=0)
        self.stdout.write('正在生成事件墙最近 7 天演示数据...')

        for payload in self.build_demo_events():
            if payload.get('environment') in EXCLUDED_DEMO_ENVIRONMENTS:
                continue
            self._record_demo(**payload)

        count = EventRecord.objects.filter(is_demo=True).count()
        self.stdout.write(self.style.SUCCESS(f'事件墙演示数据生成完成，共 {count} 条事件。'))

    def _record_demo(self, *, fallback_minutes, metadata=None, occurred_at=None, **kwargs):
        offset_minutes = self._normalize_offset_minutes(fallback_minutes, occurred_at=occurred_at)
        payload_metadata = dict(metadata or {})
        payload_metadata['demo_offset_minutes'] = offset_minutes
        if not self._is_application_release_demo(kwargs):
            kwargs['application'] = ''
        record_event(
            occurred_at=self.now - timedelta(minutes=offset_minutes),
            source_type=EventRecord.SOURCE_SEED,
            actor_type=kwargs.pop('actor_type', EventRecord.ACTOR_USER),
            actor_username=kwargs.pop('actor_username', 'system'),
            actor_display=kwargs.pop('actor_display', 'System'),
            is_demo=True,
            metadata=payload_metadata,
            **kwargs,
        )

    def _normalize_offset_minutes(self, fallback_minutes, *, occurred_at=None):
        if occurred_at:
            current = timezone.localtime(occurred_at) if timezone.is_aware(occurred_at) else timezone.make_aware(
                occurred_at,
                timezone.get_current_timezone(),
            )
            delta = self.now - current
            fallback_minutes = int(delta.total_seconds() // 60)
        return max(5, min(int(fallback_minutes), DEMO_WINDOW_MINUTES))

    def _is_application_release_demo(self, payload):
        action = str(payload.get('action') or '').strip()
        resource_type = str(payload.get('resource_type') or '').strip()
        return action in APPLICATION_RELEASE_ACTIONS or resource_type in APPLICATION_RELEASE_RESOURCE_TYPES

    def build_demo_events(self):
        return [
            {
                'module': 'ops',
                'category': 'execution',
                'action': 'deploy_start',
                'title': '发布流水线进入灰度阶段',
                'summary': '会员中心 v3.8.2 已完成构建与制品签名，正在执行灰度发布。',
                'result': EventRecord.RESULT_PENDING,
                'severity': EventRecord.SEVERITY_INFO,
                'actor_username': 'liang.yu',
                'actor_display': '梁羽',
                'resource_type': 'deployment',
                'resource_id': 'deploy-2401',
                'resource_name': '会员中心',
                'business_line': '零售',
                'environment': 'prod',
                'application': 'member-center',
                'correlation_id': 'deploy:member-center:2401',
                'related_resources': [
                    build_resource('ops', 'k8s_cluster', 'prod-hz-01', 'prod-hz-01'),
                    build_resource('cmdb', 'service', 'member-center', 'member-center'),
                ],
                'fallback_minutes': 42,
                'metadata': {'stage': '灰度发布', 'release_version': 'v3.8.2'},
            },
            {
                'module': 'ops',
                'category': 'execution',
                'action': 'deploy_finish',
                'title': '发布流水线回滚完成',
                'summary': '支付网关在生产环境触发自动回滚，已恢复上一稳定版本。',
                'result': EventRecord.RESULT_FAILED,
                'severity': EventRecord.SEVERITY_DANGER,
                'actor_username': 'chen.si',
                'actor_display': '陈思',
                'resource_type': 'deployment',
                'resource_id': 'deploy-2402',
                'resource_name': '支付网关',
                'business_line': '支付',
                'environment': 'prod',
                'application': 'payment-gateway',
                'correlation_id': 'deploy:payment-gateway:2402',
                'related_resources': [
                    build_resource('ops', 'k8s_cluster', 'prod-sh-02', 'prod-sh-02'),
                    build_resource('ops', 'alert_rule', 'latency-p99', '支付链路延迟'),
                ],
                'fallback_minutes': 138,
                'metadata': {'release_version': 'v5.2.1', 'rollback': True, 'reason': '健康检查失败'},
            },
            {
                'module': 'ops',
                'category': 'execution',
                'action': 'deploy_finish',
                'title': '发布窗口按计划完成',
                'summary': '订单服务完成生产发布，实例批次切换结束，流量已全部恢复。',
                'result': EventRecord.RESULT_SUCCESS,
                'severity': EventRecord.SEVERITY_INFO,
                'actor_username': 'zheng.wei',
                'actor_display': '郑维',
                'resource_type': 'deployment',
                'resource_id': 'deploy-2403',
                'resource_name': '订单服务',
                'business_line': '零售',
                'environment': 'prod',
                'application': 'order-service',
                'correlation_id': 'deploy:order-service:2403',
                'related_resources': [
                    build_resource('ops', 'k8s_cluster', 'prod-hz-01', 'prod-hz-01'),
                    build_resource('cmdb', 'service', 'order-service', 'order-service'),
                ],
                'fallback_minutes': 325,
                'metadata': {'release_version': 'v2.6.0', 'batch_count': 3},
            },
            {
                'module': 'sqlaudit',
                'category': 'execution',
                'action': 'execute',
                'title': 'profile_db.user_profile 表索引优化执行成功',
                'summary': 'profile_db.user_profile 表索引优化完成，执行窗口与影响行数符合预期。',
                'result': EventRecord.RESULT_SUCCESS,
                'severity': EventRecord.SEVERITY_INFO,
                'actor_username': 'wang.qi',
                'actor_display': '王琦',
                'resource_type': 'sql_order',
                'resource_id': 'sql-1901',
                'resource_name': 'profile_db.user_profile 索引优化',
                'business_line': '增长',
                'environment': 'prod',
                'application': 'profile-db',
                'correlation_id': 'sql:profile-db:1901',
                'related_resources': [
                    build_resource('sqlaudit', 'sql_datasource', 'mysql-prod-profile', '画像库 MySQL'),
                ],
                'fallback_minutes': 512,
                'metadata': {'database': 'profile_db', 'table': 'user_profile', 'sql_type': 'alter_index', 'affected_rows': 0, 'duration_ms': 1842},
            },
            {
                'module': 'sqlaudit',
                'category': 'execution',
                'action': 'execute',
                'title': 'campaign_db.campaign_activity 表分区调整执行告警',
                'summary': 'campaign_db.campaign_activity 表分区调整执行耗时偏高，已自动标记为重点复盘事件。',
                'result': EventRecord.RESULT_PARTIAL,
                'severity': EventRecord.SEVERITY_WARNING,
                'actor_username': 'sun.jie',
                'actor_display': '孙洁',
                'resource_type': 'sql_order',
                'resource_id': 'sql-1902',
                'resource_name': '活动表分区调整',
                'business_line': '增长',
                'environment': 'staging',
                'application': 'campaign-db',
                'correlation_id': 'sql:campaign-db:1902',
                'related_resources': [
                    build_resource('sqlaudit', 'sql_datasource', 'mysql-stg-campaign', '活动库 MySQL'),
                ],
                'fallback_minutes': 910,
                'metadata': {'database': 'campaign_db', 'table': 'campaign_activity', 'sql_type': 'alter_table', 'duration_ms': 12840, 'review_note': '需要低峰窗口再次执行'},
            },
            {
                'module': 'multicloud',
                'category': 'sync',
                'action': 'instance_sync',
                'title': '多云实例同步成功',
                'summary': '华东生产资源池完成实例盘点，配置状态已回填到资产目录。',
                'result': EventRecord.RESULT_SUCCESS,
                'severity': EventRecord.SEVERITY_INFO,
                'actor_username': 'system',
                'actor_display': 'System',
                'actor_type': EventRecord.ACTOR_SYSTEM,
                'resource_type': 'cloud_sync_task',
                'resource_id': 'sync-3001',
                'resource_name': '华东生产资源池',
                'business_line': '平台',
                'environment': 'prod',
                'application': 'resource-hub',
                'correlation_id': 'cloud:resource-hub:3001',
                'related_resources': [
                    build_resource('multicloud', 'cloud_environment', 'aliyun-hz-prod', '阿里云杭州生产'),
                    build_resource('cmdb', 'resource_pool', 'pool-prod-east', '华东生产资源池'),
                ],
                'fallback_minutes': 1240,
                'metadata': {'provider': 'aliyun', 'synced_instances': 186, 'drift_count': 4},
            },
            {
                'module': 'multicloud',
                'category': 'sync',
                'action': 'network_sync',
                'title': '跨云网络基线待处理',
                'summary': '跨云专线策略有 2 项待确认，已推送至运维值守队列。',
                'result': EventRecord.RESULT_PENDING,
                'severity': EventRecord.SEVERITY_WARNING,
                'actor_username': 'system',
                'actor_display': 'System',
                'actor_type': EventRecord.ACTOR_SYSTEM,
                'resource_type': 'cloud_sync_task',
                'resource_id': 'sync-3002',
                'resource_name': '跨云网络基线',
                'business_line': '平台',
                'environment': 'prod',
                'application': 'network-baseline',
                'correlation_id': 'cloud:network-baseline:3002',
                'related_resources': [
                    build_resource('multicloud', 'cloud_environment', 'hw-sh-prod', '华为云上海生产'),
                ],
                'fallback_minutes': 1610,
                'metadata': {'provider': 'hybrid', 'pending_items': 2},
            },
            {
                'module': 'marketplace',
                'category': 'execution',
                'action': 'deploy_finish',
                'title': '中间件实例扩容完成',
                'summary': 'Redis 缓存集群完成扩容，热点分片已自动迁移。',
                'result': EventRecord.RESULT_SUCCESS,
                'severity': EventRecord.SEVERITY_INFO,
                'actor_username': 'he.lin',
                'actor_display': '贺林',
                'resource_type': 'service_deployment',
                'resource_id': 'svc-4101',
                'resource_name': 'redis-prod-hot',
                'business_line': '支付',
                'environment': 'prod',
                'application': 'redis-prod-hot',
                'correlation_id': 'marketplace:redis-prod-hot:4101',
                'related_resources': [
                    build_resource('marketplace', 'service_template', 'redis-cluster', 'Redis Cluster'),
                    build_resource('ops', 'middleware_cluster', 'redis-prod-hot', 'redis-prod-hot'),
                ],
                'fallback_minutes': 1985,
                'metadata': {'deploy_mode': 'terraform', 'replicas': 6},
            },
            {
                'module': 'marketplace',
                'category': 'execution',
                'action': 'deploy_finish',
                'title': '容器运行时升级失败',
                'summary': 'Docker 节点升级过程中镜像拉取异常，已挂起后续批次。',
                'result': EventRecord.RESULT_FAILED,
                'severity': EventRecord.SEVERITY_DANGER,
                'actor_username': 'gao.nan',
                'actor_display': '高楠',
                'resource_type': 'service_deployment',
                'resource_id': 'svc-4102',
                'resource_name': 'container-runtime',
                'business_line': '平台',
                'environment': 'staging',
                'application': 'container-runtime',
                'correlation_id': 'marketplace:container-runtime:4102',
                'related_resources': [
                    build_resource('marketplace', 'service_template', 'docker-runtime', 'Docker Runtime'),
                    build_resource('ops', 'docker_host', 'docker-sh-03', 'docker-sh-03'),
                ],
                'fallback_minutes': 2330,
                'metadata': {'image': 'runtime-agent:2.4.1', 'reason': '镜像仓库超时'},
            },
            {
                'module': 'rbac',
                'category': 'system',
                'action': 'sync_role',
                'title': '权限基线同步完成',
                'summary': 'Autotoll DevOps 运维管理员角色与菜单权限完成同步。',
                'result': EventRecord.RESULT_SUCCESS,
                'severity': EventRecord.SEVERITY_INFO,
                'actor_username': 'system',
                'actor_display': 'System',
                'actor_type': EventRecord.ACTOR_SYSTEM,
                'resource_type': 'rbac_role',
                'resource_id': 'ops-admin',
                'resource_name': '运维管理员',
                'business_line': '平台',
                'environment': 'shared',
                'application': 'sxdevops',
                'correlation_id': 'rbac:ops-admin',
                'related_resources': [
                    build_resource('rbac', 'menu_group', 'ops-console', '运维控制台'),
                ],
                'fallback_minutes': 2815,
                'metadata': {'changed_permissions': 12},
            },
            {
                'module': 'cmdb',
                'category': 'resource_change',
                'action': 'asset_update',
                'title': 'CMDB 资产属性更新',
                'summary': '支付业务资源池补齐可用区与负责人信息，资产画像更加完整。',
                'result': EventRecord.RESULT_SUCCESS,
                'severity': EventRecord.SEVERITY_INFO,
                'actor_username': 'zhou.xin',
                'actor_display': '周昕',
                'resource_type': 'cmdb_asset',
                'resource_id': 'asset-5201',
                'resource_name': 'payment-pool-a',
                'business_line': '支付',
                'environment': 'prod',
                'application': 'resource-directory',
                'correlation_id': 'cmdb:payment-pool-a:5201',
                'related_resources': [
                    build_resource('cmdb', 'resource_pool', 'payment-pool-a', 'payment-pool-a'),
                ],
                'fallback_minutes': 3320,
                'metadata': {'updated_fields': ['owner', 'zone', 'sla_level']},
            },
            {
                'module': 'ops',
                'category': 'execution',
                'action': 'host_task',
                'title': '批量主机任务部分成功',
                'summary': '日志采集 Agent 升级任务覆盖 48 台主机，其中 3 台待人工处理。',
                'result': EventRecord.RESULT_PARTIAL,
                'severity': EventRecord.SEVERITY_WARNING,
                'actor_username': 'liu.min',
                'actor_display': '刘敏',
                'resource_type': 'host_task',
                'resource_id': 'task-6101',
                'resource_name': '升级日志采集 Agent',
                'business_line': '平台',
                'environment': 'prod',
                'application': 'log-agent',
                'correlation_id': 'host-task:6101',
                'related_resources': [
                    build_resource('ops', 'host_group', 'prod-log-collectors', 'prod-log-collectors'),
                ],
                'fallback_minutes': 3810,
                'metadata': {'target_count': 48, 'success_count': 45, 'failed_count': 3},
            },
            {
                'module': 'ops',
                'category': 'workflow',
                'action': 'approval_pending',
                'title': '事务工单等待审批',
                'summary': '生产库账号白名单调整已提交，等待值班负责人审批。',
                'result': EventRecord.RESULT_PENDING,
                'severity': EventRecord.SEVERITY_WARNING,
                'actor_username': 'lin.qiao',
                'actor_display': '林乔',
                'resource_type': 'transaction_ticket',
                'resource_id': 'ticket-7101',
                'resource_name': '生产库白名单调整',
                'business_line': '支付',
                'environment': 'prod',
                'application': 'db-access',
                'correlation_id': 'ticket:7101',
                'related_resources': [
                    build_resource('ops', 'approval_flow', 'flow-db-access', '数据库访问审批流'),
                ],
                'fallback_minutes': 4260,
                'metadata': {'ticket_type': 'access_change', 'current_node': '安全审批'},
            },
            {
                'module': 'ops',
                'category': 'workflow',
                'action': 'approval_finish',
                'title': '应用发布单审批通过',
                'summary': '结算中心热修复发布单已完成审批，自动进入执行队列。',
                'result': EventRecord.RESULT_SUCCESS,
                'severity': EventRecord.SEVERITY_INFO,
                'actor_username': 'xie.ning',
                'actor_display': '谢宁',
                'resource_type': 'deployment',
                'resource_id': 'deploy-2404',
                'resource_name': '结算中心',
                'business_line': '支付',
                'environment': 'prod',
                'application': 'settlement-center',
                'correlation_id': 'deploy:settlement-center:2404',
                'related_resources': [
                    build_resource('ops', 'approval_flow', 'flow-release-prod', '生产发布审批流'),
                ],
                'fallback_minutes': 4690,
                'metadata': {'release_version': 'v1.9.8-hotfix', 'approver_count': 2},
            },
            {
                'module': 'ops',
                'category': 'execution',
                'action': 'middleware_rebalance',
                'title': '消息堆积处置完成',
                'summary': 'RocketMQ 审计链路完成消费者重平衡，积压水位已恢复正常。',
                'result': EventRecord.RESULT_SUCCESS,
                'severity': EventRecord.SEVERITY_WARNING,
                'actor_username': 'ops-bot',
                'actor_display': 'Ops Bot',
                'resource_type': 'middleware_cluster',
                'resource_id': 'audit-mq',
                'resource_name': 'audit-mq',
                'business_line': '平台',
                'environment': 'prod',
                'application': 'audit-mq',
                'correlation_id': 'middleware:audit-mq',
                'related_resources': [
                    build_resource('ops', 'middleware_cluster', 'audit-mq', 'audit-mq'),
                    build_resource('ops', 'log_datasource', 'audit-logs', 'audit-logs'),
                ],
                'fallback_minutes': 5235,
                'metadata': {'queue_lag_before': 12843, 'queue_lag_after': 312},
            },
            {
                'module': 'multicloud',
                'category': 'resource_change',
                'action': 'environment_sync',
                'title': '云环境账实核对完成',
                'summary': '上海预发环境完成账实核对，冗余弹性公网 IP 已标记回收。',
                'result': EventRecord.RESULT_SUCCESS,
                'severity': EventRecord.SEVERITY_INFO,
                'actor_username': 'system',
                'actor_display': 'System',
                'actor_type': EventRecord.ACTOR_SYSTEM,
                'resource_type': 'cloud_environment',
                'resource_id': 'hw-sh-staging',
                'resource_name': '华为云上海预发',
                'business_line': '平台',
                'environment': 'staging',
                'application': 'resource-hub',
                'correlation_id': 'cloud-environment:hw-sh-staging',
                'related_resources': [
                    build_resource('multicloud', 'cloud_credential', 'hw-main', '华为云主账号'),
                ],
                'fallback_minutes': 6110,
                'metadata': {'reclaimed_eip': 3, 'drift_count': 0},
            },
            {
                'module': 'sqlaudit',
                'category': 'workflow',
                'action': 'review_pending',
                'title': 'order_db.order_archive 表字段清理等待复核',
                'summary': 'order_db.order_archive 表字段清理申请已提交，等待 DBA 复核执行窗口。',
                'result': EventRecord.RESULT_PENDING,
                'severity': EventRecord.SEVERITY_WARNING,
                'actor_username': 'feng.rui',
                'actor_display': '冯睿',
                'resource_type': 'sql_order',
                'resource_id': 'sql-1903',
                'resource_name': 'order_db.order_archive 字段清理',
                'business_line': '零售',
                'environment': 'prod',
                'application': 'order-db',
                'correlation_id': 'sql:order-db:1903',
                'related_resources': [
                    build_resource('sqlaudit', 'sql_datasource', 'mysql-prod-order', '订单库 MySQL'),
                ],
                'fallback_minutes': 7080,
                'metadata': {'database': 'order_db', 'table': 'order_archive', 'sql_type': 'alter_table', 'current_node': 'DBA 复核'},
            },
        ]
