# Generated by Django 5.2.15 on 2026-07-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProbeAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_kind', models.CharField(choices=[('host', '主机'), ('database', '数据库')], max_length=16, verbose_name='目标类型')),
                ('target_id', models.IntegerField(verbose_name='目标 ID（ops.Host.id 或 sqlaudit.DataSource.id）')),
                ('last_status', models.CharField(choices=[('ok', '成功'), ('error', '错误'), ('timeout', '超时'), ('misconfigured', '凭据缺失')], max_length=16, verbose_name='最近状态')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='最近错误')),
                ('last_duration_ms', models.IntegerField(default=0, verbose_name='最近耗时 ms')),
                ('last_collected_at', models.DateTimeField(auto_now=True, verbose_name='最近采集时间')),
            ],
            options={
                'verbose_name': '采集审计',
                'verbose_name_plural': '采集审计',
                'db_table': 'monitoring_probe_audit',
                'indexes': [models.Index(fields=['target_kind', 'last_collected_at'], name='monitoring__target__2c6489_idx')],
                'unique_together': {('target_kind', 'target_id')},
            },
        ),
    ]
